version: "3"
volumes:
  rendezvous:
services:
  rendezvous:
    build: rendezvous
    ports:
      - "80:3000"
    volumes:
      - rendezvous:/data
  appinventorserver:
    build:
      context: .
      args:
        VERSION: v185a
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
